name: validate OAS

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          npm install -g ibm-openapi-validator
          npm lint-openapi --version
          pip install yamllint
          yamllint --version
      - name: Lint
        run: |
          cd docs/openapi
          set -x
          yamllint -c yamllint-config.yml -v programmable-network.yaml
          yamllint -c yamllint-config.yml -v programmable-network-codegen.yaml
          lint-openapi -c .validaterc --colors -v programmable-network.yaml
          lint-openapi -c .validaterc --colors -v programmable-network-codegen.yaml
